language: node_js 
node_js:
  - "0.1"
  - "iojs"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"

install:
  - npm install

before_script:
  - npm install eslint --save-dev 


script:
  - npm run lint

